ebs-ds: ds/avltree.c File Reference
avltree.c File Reference
Implementation of the AVL binary search tree.
#include "avltree.h"
Functions
static AVLT_HEIGHT_t _node_height (avlt_node_t *node)
static AVLT_HEIGHT_t _node_balance_factor (avlt_node_t *node)
static avlt_node_t * _node_rotate_leftleft (avlt_node_t *node)
static avlt_node_t * _node_rotate_leftright (avlt_node_t *node)
static avlt_node_t * _node_rotate_rightleft (avlt_node_t *node)
static avlt_node_t * _node_rotate_rightright (avlt_node_t *node)
static avlt_node_t * _node_balance (avlt_node_t *node)
static void _tree_balance (avlt_t *tree)
void avlt_init_node (avlt_node_t *node, uint16_t key, void *content)
void avlt_insert_node (avlt_t *tree, avlt_node_t *node)
avlt_node_t * avlt_find_node (avlt_t *tree, uint16_t key)
Detailed Description
Implementation of the AVL binary search tree.
Implementation of the AVL tree data structure.
Based on the implemenation at https://gist.github.com/tonious/1377768
See also
avltree.h
avltree.h
Definition in file avltree.c.
Function Documentation
_node_balance()
static avlt_node_t * _node_balance (avlt_node_t * node) static
Definition at line 124 of file avltree.c.
References _node_balance(), _node_balance_factor(), _node_rotate_leftleft(), _node_rotate_leftright(), _node_rotate_rightleft(), _node_rotate_rightright(), AVLT_HEIGHT_t, AVLT_NODE_t::left, and AVLT_NODE_t::right.
Referenced by _node_balance(), and _tree_balance().
_node_balance_factor()
static AVLT_HEIGHT_t _node_balance_factor (avlt_node_t * node) static
Definition at line 67 of file avltree.c.
References _node_height(), AVLT_HEIGHT_t, AVLT_NODE_t::left, and AVLT_NODE_t::right.
Referenced by _node_balance().
_node_height()
static AVLT_HEIGHT_t _node_height (avlt_node_t * node) static
Definition at line 55 of file avltree.c.
References _node_height(), AVLT_HEIGHT_t, AVLT_NODE_t::left, and AVLT_NODE_t::right.
Referenced by _node_balance_factor(), and _node_height().
_node_rotate_leftleft()
static avlt_node_t * _node_rotate_leftleft (avlt_node_t * node) static
Definition at line 78 of file avltree.c.
References AVLT_NODE_t::left, and AVLT_NODE_t::right.
Referenced by _node_balance().
_node_rotate_leftright()
static avlt_node_t * _node_rotate_leftright (avlt_node_t * node) static
Definition at line 88 of file avltree.c.
References AVLT_NODE_t::left, and AVLT_NODE_t::right.
Referenced by _node_balance().
_node_rotate_rightleft()
static avlt_node_t * _node_rotate_rightleft (avlt_node_t * node) static
Definition at line 101 of file avltree.c.
References AVLT_NODE_t::left, and AVLT_NODE_t::right.
Referenced by _node_balance().
_node_rotate_rightright()
static avlt_node_t * _node_rotate_rightright (avlt_node_t * node) static
Definition at line 114 of file avltree.c.
References AVLT_NODE_t::left, and AVLT_NODE_t::right.
Referenced by _node_balance().
_tree_balance()
static void _tree_balance (avlt_t * tree) static
Definition at line 159 of file avltree.c.
References _node_balance(), and AVLT_t::root.
Referenced by avlt_insert_node().
avlt_find_node()
avlt_node_t * avlt_find_node (avlt_t * tree, uint16_t key)
Definition at line 200 of file avltree.c.
References AVLT_NODE_t::key, AVLT_NODE_t::left, AVLT_NODE_t::right, and AVLT_t::root.
avlt_init_node()
void avlt_init_node (avlt_node_t * node, uint16_t key, void * content)
Definition at line 46 of file avltree.c.
References AVLT_NODE_t::content, AVLT_NODE_t::height, AVLT_NODE_t::key, AVLT_NODE_t::left, and AVLT_NODE_t::right.
avlt_insert_node()
void avlt_insert_node (avlt_t * tree, avlt_node_t * node)
Definition at line 167 of file avltree.c.
References _tree_balance(), AVLT_NODE_t::key, AVLT_NODE_t::left, AVLT_NODE_t::right, and AVLT_t::root.