ebs-ds: ds/bytebuf.h File Reference
bytebuf.h File Reference
Interface and usage of bytebuf buffers.
#include <stdint.h>
Data Structures
struct BYTEBUF
Primary bytebuf struct typedef.
Macros
Generic Write Tokens
#define BYTEBUF_LOCK_OPEN 0
#define BYTEBUF_TOKEN_PRINT 1
#define BYTEBUF_TOKEN_SCHAR 2
Typedefs
typedef struct BYTEBUF bytebuf
Primary bytebuf struct typedef.
Functions
void bytebuf_vInit (uint8_t *bufferp, uint8_t size, bytebuf *bytebufp)
void bytebuf_vFlush (bytebuf *bytebufp)
static uint8_t bytebuf_cPopulation (bytebuf *bytebufp)
static uint8_t bytebuf_cGetFree (bytebuf *bytebufp)
static uint8_t bytebuf_cPushChunkLen (bytebuf *bytebufp, uint8_t *past_rollover)
Return the number of bytes that can be written contiguously. You still need to acquire a lock if you want to write into it.
static uint8_t bytebuf_cPopChunkLen (bytebuf *bytebufp, uint8_t *at_rollover)
Return the number of bytes that can be read contiguously.
uint8_t bytebuf_cPushReqLock (bytebuf *bytebufp, uint8_t length, uint8_t token)
uint8_t bytebuf_cPushReqBlindLock (bytebuf *bytebufp, uint8_t token)
uint8_t bytebuf_cPushRelinquishLock (bytebuf *bytebufp, uint8_t token)
uint8_t bytebuf_cWriteByte (bytebuf *bytebufp, uint8_t byte)
uint8_t bytebuf_cPushByte (bytebuf *bytebufp, uint8_t byte, uint8_t token)
uint8_t bytebuf_cPushLen (bytebuf *bytebufp, void *sp, uint8_t len, uint8_t token)
uint8_t bytebuf_cPopByte (bytebuf *bytebufp)
uint8_t bytebuf_cPopLen (bytebuf *bytebufp, void *dp, uint8_t len)
uint8_t bytebuf_cCopyLen (bytebuf *bytebufp, void *dp, uint8_t len)
uint8_t bytebuf_cPopChunk (bytebuf *bytebufp, uint8_t len)
Mark the next n outbytes as handled. This function is intended to be used with DMA or other functions which read the array in the background. After the read is complete, the buffer should be informed via this function that the read data can be discarded from the buffer. ,.
Detailed Description
Interface and usage of bytebuf buffers.
This library provides a bytebuf structure and associated functions to implement a circular byte buffer. The design of the buffer is intended to support continuous byte-wide datastreams. A simple locking mechanism for writes is included.
The typical application of such a buffer is when one or more data sources (producers) are writing to a single sink (consumer). In the general case, the buffer is instantiated at and by the consumer, while the producers use their respective tokens to write to the buffer.
While errors are reported, for optimal use implementations should ensure that the buffers are large enough for the consumers to handle all of the produced data before an overflow occurs.
A bytebuf buffer can be at-most 255 bytes long. For longer buffers, some datatypes need to be changed from uint8_t to uint16_t. This will have a performance penalty on uCs with an 8-bit bus.
See also
bytebuf.c
Definition in file bytebuf.h.
Data Structure Documentation
BYTEBUF
struct BYTEBUF
Primary bytebuf struct typedef.
The core of the bytebuf implementation, this type contains bytebuf metadata and control information. This struct should be created by instantiating a variable at the consumer of this type, and calling bytebuf_vInit().
This struct does not contain the actual data but has a pointer to a byte array which should be separately created and contains the actual data.
Definition at line 77 of file bytebuf.h.
Data Fields
uint8_t * _bufp Pointer to the start of the underlying buffer.
uint8_t * _inp Pointer to the current write location.
uint8_t _lock Token which holds the write lock at present.
uint8_t _locklen Number of additional bytes for which the lock is valid.
uint8_t * _outp Pointer to the current read location.
volatile uint8_t _population Number of bytes presently in the buffer.
uint8_t _size Size of buffer.
Macro Definition Documentation
BYTEBUF_LOCK_OPEN
#define BYTEBUF_LOCK_OPEN 0
Definition at line 58 of file bytebuf.h.
BYTEBUF_TOKEN_PRINT
#define BYTEBUF_TOKEN_PRINT 1
Definition at line 59 of file bytebuf.h.
BYTEBUF_TOKEN_SCHAR
#define BYTEBUF_TOKEN_SCHAR 2
Definition at line 60 of file bytebuf.h.
Typedef Documentation
bytebuf
typedef struct BYTEBUF bytebuf
Primary bytebuf struct typedef.
The core of the bytebuf implementation, this type contains bytebuf metadata and control information. This struct should be created by instantiating a variable at the consumer of this type, and calling bytebuf_vInit().
This struct does not contain the actual data but has a pointer to a byte array which should be separately created and contains the actual data.
Function Documentation
bytebuf_cCopyLen()
uint8_t bytebuf_cCopyLen (bytebuf * bytebufp, void * dp, uint8_t len)
Copy a length of data from a bytebuf using the platform's memcpy function.
You should ensure that that number of bytes actually exists in the buffer to be read.
See also
bytebuf_cPopulation()
Parameters
bytebufp Pointer to the bytebuf structure.
dp Pointer to the destination buffer.
len Number of bytes to copy.
Returns
0 for failed read, 1 for successful copy.
Definition at line 218 of file bytebuf.c.
References BYTEBUF::_bufp, BYTEBUF::_outp, BYTEBUF::_population, and bytebuf_cPopChunkLen().
bytebuf_cGetFree()
static uint8_t bytebuf_cGetFree (bytebuf * bytebufp) inline static
Return the number of bytes that can be written into the buffer right now. You still need to acquire a lock if you want to write into it.
See also
bytebuf_cPushReqLock()
Parameters
bytebufp Pointer to the bytebuf structure.
Returns
The number of empty bytes left in the buffer.
Definition at line 126 of file bytebuf.h.
References BYTEBUF::_population, and BYTEBUF::_size.
Referenced by bytebuf_cPushReqBlindLock(), bytebuf_cPushReqLock(), and bytebuf_cWriteByte().
bytebuf_cPopByte()
uint8_t bytebuf_cPopByte (bytebuf * bytebufp)
Pop a byte from the bytebuf. You should make sure that there actually is a byte to be read first.
See also
cbytebuf_population()
Parameters
bytebufp Pointer to the bytebuf structure.
Returns
The byte that got popped, or 0 by default if there wasn't one.
Warning
return value of 0 does not necessarily mean an error occured.
Definition at line 180 of file bytebuf.c.
References BYTEBUF::_bufp, BYTEBUF::_outp, BYTEBUF::_population, and BYTEBUF::_size.
bytebuf_cPopChunk()
uint8_t bytebuf_cPopChunk (bytebuf * bytebufp, uint8_t len)
Mark the next n outbytes as handled. This function is intended to be used with DMA or other functions which read the array in the background. After the read is complete, the buffer should be informed via this function that the read data can be discarded from the buffer. ,.
See also
bytebuf_cPopChunkLen()
Parameters
bytebufp Pointer to the bytebuf structure.
len The number of bytes that should be popped.
Returns
0 if insufficient bytes to pop, the number of bytes popped otherwise.
Definition at line 236 of file bytebuf.c.
References BYTEBUF::_bufp, BYTEBUF::_outp, BYTEBUF::_population, and bytebuf_cPopChunkLen().
bytebuf_cPopChunkLen()
static uint8_t bytebuf_cPopChunkLen (bytebuf * bytebufp, uint8_t * at_rollover) inline static
Return the number of bytes that can be read contiguously.
See also
bytebuf_cPopChunk()
Parameters
bytebufp Pointer to the bytebuf structure.
at_rollover Pointer to uint8_t in which to store rollover flag.
Returns
The number of bytes that can be read contiguously.
Definition at line 167 of file bytebuf.h.
Referenced by bytebuf_cCopyLen(), bytebuf_cPopChunk(), and bytebuf_cPopLen().
bytebuf_cPopLen()
uint8_t bytebuf_cPopLen (bytebuf * bytebufp, void * dp, uint8_t len)
Pop a length of data from a bytebuf using the platform's memcpy function.
You should ensure that that number of bytes actually exists in the buffer to be read.
See also
bytebuf_cPopulation()
Parameters
bytebufp Pointer to the bytebuf structure.
dp Pointer to the destination buffer.
len Number of bytes to pop.
Returns
0 for failed read, 1 for successful read.
Definition at line 197 of file bytebuf.c.
References BYTEBUF::_bufp, BYTEBUF::_outp, BYTEBUF::_population, and bytebuf_cPopChunkLen().
bytebuf_cPopulation()
static uint8_t bytebuf_cPopulation (bytebuf * bytebufp) inline static
Return the number of bytes present in the buffer to be read.
Parameters
bytebufp Pointer to the bytebuf structure.
Returns
The number of bytes left in the buffer to be read.
Definition at line 112 of file bytebuf.h.
References BYTEBUF::_population.
bytebuf_cPushByte()
uint8_t bytebuf_cPushByte (bytebuf * bytebufp, uint8_t byte, uint8_t token)
Push a single byte into the bytebuf. You should already hold the write lock to do this.
See also
bytebuf_cPushReqLock()
Parameters
bytebufp Pointer to the bytebuf structure.
byte Byte to be written in.
token Identifier against which you own the lock.
Returns
0 for failed write, 1 for successful write.
Definition at line 128 of file bytebuf.c.
References BYTEBUF::_bufp, BYTEBUF::_inp, BYTEBUF::_lock, BYTEBUF::_locklen, BYTEBUF::_population, BYTEBUF::_size, and BYTEBUF_LOCK_OPEN.
bytebuf_cPushChunkLen()
static uint8_t bytebuf_cPushChunkLen (bytebuf * bytebufp, uint8_t * past_rollover) inline static
Return the number of bytes that can be written contiguously. You still need to acquire a lock if you want to write into it.
See also
bytebuf_cPushChunk()
Parameters
bytebufp Pointer to the bytebuf structure.
past_rollover Pointer to uint8_t in which to store rollover flag.
Returns
The number of bytes that can be written contiguously.
Definition at line 142 of file bytebuf.h.
References BYTEBUF::_population, and BYTEBUF::_size.
Referenced by bytebuf_cPushLen().
bytebuf_cPushLen()
uint8_t bytebuf_cPushLen (bytebuf * bytebufp, void * sp, uint8_t len, uint8_t token)
Push a length of data into a bytebuf. You should already hold the write lock to do this.
See also
bytebuf_cPushReqLock()
Parameters
bytebufp Pointer to the bytebuf structure.
sp Pointer to the source buffer.
len Number of bytes to push in.
token Identifier against which you own the lock.
Returns
0 for failed write, 1 for successful write.
Definition at line 154 of file bytebuf.c.
References BYTEBUF::_bufp, BYTEBUF::_inp, BYTEBUF::_lock, BYTEBUF::_locklen, BYTEBUF::_population, bytebuf_cPushChunkLen(), and BYTEBUF_LOCK_OPEN.
bytebuf_cPushRelinquishLock()
uint8_t bytebuf_cPushRelinquishLock (bytebuf * bytebufp, uint8_t token)
Relinquish a write lock on a bytebuf. Actual writing is done using other functions.
See also
bytebuf_cPushReqLock()
Parameters
bytebufp Pointer to the bytebuf structure.
token An identifier against which the lock was issued.
Returns
0 for incorrect token, 1 for lock relinquished, 2 for already open.
Definition at line 89 of file bytebuf.c.
References BYTEBUF_LOCK_OPEN.
bytebuf_cPushReqBlindLock()
uint8_t bytebuf_cPushReqBlindLock (bytebuf * bytebufp, uint8_t token)
Request a write lock on a bytebuf for an unspecified length. Actual writing is done using other functions.
See also
bytebuf_cPush()
bytebuf_cPushLen()
Parameters
bytebufp Pointer to the bytebuf structure.
token An identifier against which to issue the lock.
Returns
0 for lock denied, number of characters free for granted.
Definition at line 72 of file bytebuf.c.
References bytebuf_cGetFree(), and BYTEBUF_LOCK_OPEN.
bytebuf_cPushReqLock()
uint8_t bytebuf_cPushReqLock (bytebuf * bytebufp, uint8_t length, uint8_t token)
Request a write lock on a bytebuf for a specific length. Actual writing is done using other functions.
See also
bytebuf_cPush()
bytebuf_cPushLen()
Parameters
bytebufp Pointer to the bytebuf structure.
length Number of bytes you want to write.
token An identifier against which to issue the lock.
Returns
0 for lock denied, 1 for lock issued.
Definition at line 57 of file bytebuf.c.
References bytebuf_cGetFree(), and BYTEBUF_LOCK_OPEN.
bytebuf_cWriteByte()
uint8_t bytebuf_cWriteByte (bytebuf * bytebufp, uint8_t byte)
Write a single byte into the bytebuf, clobbering the oldest value in the buffer if there isn't room. Locking isn't used.
Parameters
bytebufp Pointer to the bytebuf structure.
byte Byte to be written in.
Returns
0 for failed write, 1 for successful write.
Definition at line 102 of file bytebuf.c.
References BYTEBUF::_bufp, BYTEBUF::_inp, BYTEBUF::_outp, BYTEBUF::_population, BYTEBUF::_size, and bytebuf_cGetFree().
bytebuf_vFlush()
void bytebuf_vFlush (bytebuf * bytebufp)
Flush a buffer and reset it to its pristine state.
Warning
Any locks held on the buffer will disappear and holder is not informed.
Any data present in the data will be lost.
Parameters
bytebufp Pointer to the bytebuf structure.
Definition at line 46 of file bytebuf.c.
References BYTEBUF_LOCK_OPEN.
Referenced by bytebuf_vInit().
bytebuf_vInit()
void bytebuf_vInit (uint8_t * bufferp, uint8_t size, bytebuf * bytebufp)
Initialize a bytebuf structure using an externally supplied (and allocated) memory array.
Parameters
bufferp Pointer to the array; should be in the heap and not in a task stack.
size Size of the array. Beware : we have no good way to check this later.
bytebufp Pointer to the bytebuf structure to be initialized.
Definition at line 37 of file bytebuf.c.
References bytebuf_vFlush().