ebs-ds: ds/hashmap.h File Reference
hashmap.h File Reference
Interface and usage of Hash Tables.
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
Data Structures
struct hashmap_entry_t
struct hashmap_t
Macros
#define HASHMAP_SIZE_t uint8_t
Functions
void hashmap_init (hashmap_t *map, hashmap_entry_t *table, size_t capacity)
void hashmap_clear (hashmap_t *map)
bool hashmap_insert (hashmap_t *map, uint16_t key, void *value, size_t len)
hashmap_entry_t * hashmap_get (hashmap_t *map, uint16_t key)
bool hashmap_remove (hashmap_t *map, uint16_t key)
Detailed Description
Interface and usage of Hash Tables.
See also
hashmap.c
Definition in file hashmap.h.
Data Structure Documentation
hashmap_entry_t
struct hashmap_entry_t
Definition at line 40 of file hashmap.h.
Data Fields
bool in_use
uint16_t key
size_t len
void * ptr
hashmap_t
struct hashmap_t
Definition at line 47 of file hashmap.h.
Data Fields
HASHMAP_SIZE_t count
HASHMAP_SIZE_t size
hashmap_entry_t * table
Macro Definition Documentation
HASHMAP_SIZE_t
#define HASHMAP_SIZE_t uint8_t
Definition at line 37 of file hashmap.h.
Function Documentation
hashmap_clear()
void hashmap_clear (hashmap_t * map)
Definition at line 42 of file hashmap.c.
References hashmap_t::count, hashmap_t::size, and hashmap_t::table.
hashmap_get()
hashmap_entry_t * hashmap_get (hashmap_t * map, uint16_t key)
Definition at line 69 of file hashmap.c.
References hash_function(), hashmap_entry_t::in_use, hashmap_entry_t::key, hashmap_t::size, and hashmap_t::table.
hashmap_init()
void hashmap_init (hashmap_t * map, hashmap_entry_t * table, size_t capacity)
Definition at line 36 of file hashmap.c.
References hashmap_t::count, hashmap_t::size, and hashmap_t::table.
hashmap_insert()
bool hashmap_insert (hashmap_t * map, uint16_t key, void * value, size_t len)
Definition at line 47 of file hashmap.c.
References hashmap_t::count, hash_function(), hashmap_entry_t::in_use, hashmap_entry_t::key, hashmap_entry_t::ptr, hashmap_t::size, and hashmap_t::table.
hashmap_remove()
bool hashmap_remove (hashmap_t * map, uint16_t key)
Definition at line 88 of file hashmap.c.
References hashmap_t::count, hash_function(), hashmap_entry_t::in_use, hashmap_entry_t::key, hashmap_entry_t::len, hashmap_entry_t::ptr, hashmap_t::size, and hashmap_t::table.